In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from datetime import date
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(r"D:\AI_VIETNAM\file\flight_cleaned.csv")

df

,code_name,type,from,to,Month_from,Day_from,time_from,Month_to,Day_to,time_to,Sum of Sum of f_price,Sum of Sum of fees,Sum of Sum of total_price
0,Vietnam Airlines,Economy (EG)-M,Hà Nội,TP HCM,April,6,1899-12-30 07:00:00,April,6,1899-12-30 09:15:00,5658000,1806000,7464000
1,Vietnam Airlines,Economy (EG)-M,TP HCM,Hà Nội,May,3,1899-12-30 09:00:00,May,3,1899-12-30 11:10:00,5658000,1806000,7464000
2,Vietnam Airlines,Business (BF)-J,Phú Quốc,Hà Nội,April,4,1899-12-30 03:45:00,April,4,1899-12-30 06:00:00,5309000,1151000,6460000
3,Vietnam Airlines,Business (BF)-J,Phú Quốc,Hà Nội,April,25,1899-12-30 07:00:00,April,25,1899-12-30 09:15:00,5309000,1151000,6460000
4,Vietnam Airlines,Business (BF)-J,Hà Nội,Phú Quốc,April,30,1899-12-30 03:20:00,April,30,1899-12-30 05:35:00,5309000,1151000,6460000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19444,Vietravel Airlines,Promo1 (P) - Vé không hoàn,TP HCM,Đà Nẵng,April,14,1899-12-30 04:00:00,April,14,1899-12-30 05:20:00,36000,644600,680600
19445,Vietravel Airlines,Promo1 (P) - Vé không hoàn,Đà Nẵng,Hà Nội,April,14,1899-12-30 07:00:00,April,14,1899-12-30 08:20:00,36000,644600,680600
19446,Vietravel Airlines,Promo1 (P) - Vé không hoàn,TP HCM,Đà Nẵng,April,14,1899-12-30 07:35:00,April,14,1899-12-30 08:55:00,36000,644600,680600
19447,Vietravel Airlines,Promo1 (P) - Vé không hoàn,Đà Nẵng,TP HCM,April,14,1899-12-30 10:35:00,April,14,1899-12-30 12:05:00,36000,644600,680600
19448,Vietravel Airlines,Promo1 (P) - Vé không hoàn,Hà Nội,Đà Nẵng,April,14,1899-12-30 12:10:00,April,14,1899-12-30 01:30:00,36000,644600,680600

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19449 entries, 0 to 19448
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   code_name                  19449 non-null  object
 1   type                       19449 non-null  object
 2   from                       19449 non-null  object
 3   to                         19449 non-null  object
 4   Month_from                 19449 non-null  object
 5   Day_from                   19449 non-null  int64
 6   time_from                  19449 non-null  object
 7   Month_to                   19449 non-null  object
 8   Day_to                     19449 non-null  int64
 9   time_to                    19449 non-null  object
 10  Sum of Sum of f_price      19449 non-null  int64
 11  Sum of Sum of fees         19449 non-null  int64
 12  Sum of Sum of total_price  19449 non-null  int64
dtypes: int64(5), object(8)
memory usage: 1.9+ MB

In [4]:
df.columns

Index(['code_name', 'type', 'from', 'to', 'Month_from', 'Day_from',
       'time_from', 'Month_to', 'Day_to', 'time_to', 'Sum of Sum of f_price',
       'Sum of Sum of fees', 'Sum of Sum of total_price'],
      dtype='object')

In [5]:
# Check duplicated
df.duplicated().sum()

np.int64(0)

In [6]:
# Số lượng loại type khác nhau
len(df['type'].unique())

42

In [7]:
X = df[['code_name', 'type', 'from', 'to', 'Month_from', 'Day_from',
       'time_from', 'Month_to', 'Day_to', 'time_to']]
y = df[['Sum of Sum of total_price']]
X

,code_name,type,from,to,Month_from,Day_from,time_from,Month_to,Day_to,time_to
0,Vietnam Airlines,Economy (EG)-M,Hà Nội,TP HCM,April,6,1899-12-30 07:00:00,April,6,1899-12-30 09:15:00
1,Vietnam Airlines,Economy (EG)-M,TP HCM,Hà Nội,May,3,1899-12-30 09:00:00,May,3,1899-12-30 11:10:00
2,Vietnam Airlines,Business (BF)-J,Phú Quốc,Hà Nội,April,4,1899-12-30 03:45:00,April,4,1899-12-30 06:00:00
3,Vietnam Airlines,Business (BF)-J,Phú Quốc,Hà Nội,April,25,1899-12-30 07:00:00,April,25,1899-12-30 09:15:00
4,Vietnam Airlines,Business (BF)-J,Hà Nội,Phú Quốc,April,30,1899-12-30 03:20:00,April,30,1899-12-30 05:35:00
...,...,...,...,...,...,...,...,...,...,...
19444,Vietravel Airlines,Promo1 (P) - Vé không hoàn,TP HCM,Đà Nẵng,April,14,1899-12-30 04:00:00,April,14,1899-12-30 05:20:00
19445,Vietravel Airlines,Promo1 (P) - Vé không hoàn,Đà Nẵng,Hà Nội,April,14,1899-12-30 07:00:00,April,14,1899-12-30 08:20:00
19446,Vietravel Airlines,Promo1 (P) - Vé không hoàn,TP HCM,Đà Nẵng,April,14,1899-12-30 07:35:00,April,14,1899-12-30 08:55:00
19447,Vietravel Airlines,Promo1 (P) - Vé không hoàn,Đà Nẵng,TP HCM,April,14,1899-12-30 10:35:00,April,14,1899-12-30 12:05:00
19448,Vietravel Airlines,Promo1 (P) - Vé không hoàn,Hà Nội,Đà Nẵng,April,14,1899-12-30 12:10:00,April,14,1899-12-30 01:30:00

In [8]:
# Phân loại is holiday và ngày thường. Trong power BI các ngày có total_sales cao là 29/4-3-5
# Ta tạo thêm feature mới bằng cách tăng số cột nhưng số dòng thì sẽ ko đổi
condition = (
    ((df['Month_from'] == 'April') & (df['Day_from'] >= 27)) | 
    ((df['Month_from'] == 'May') & (df['Day_from'] <= 3))
)
X['is_holiday'] = np.where(condition, 1, 0)
X

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_10628\1556119632.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['is_holiday'] = np.where(condition, 1, 0)

,code_name,type,from,to,Month_from,Day_from,time_from,Month_to,Day_to,time_to,is_holiday
0,Vietnam Airlines,Economy (EG)-M,Hà Nội,TP HCM,April,6,1899-12-30 07:00:00,April,6,1899-12-30 09:15:00,0
1,Vietnam Airlines,Economy (EG)-M,TP HCM,Hà Nội,May,3,1899-12-30 09:00:00,May,3,1899-12-30 11:10:00,1
2,Vietnam Airlines,Business (BF)-J,Phú Quốc,Hà Nội,April,4,1899-12-30 03:45:00,April,4,1899-12-30 06:00:00,0
3,Vietnam Airlines,Business (BF)-J,Phú Quốc,Hà Nội,April,25,1899-12-30 07:00:00,April,25,1899-12-30 09:15:00,0
4,Vietnam Airlines,Business (BF)-J,Hà Nội,Phú Quốc,April,30,1899-12-30 03:20:00,April,30,1899-12-30 05:35:00,1
...,...,...,...,...,...,...,...,...,...,...,...
19444,Vietravel Airlines,Promo1 (P) - Vé không hoàn,TP HCM,Đà Nẵng,April,14,1899-12-30 04:00:00,April,14,1899-12-30 05:20:00,0
19445,Vietravel Airlines,Promo1 (P) - Vé không hoàn,Đà Nẵng,Hà Nội,April,14,1899-12-30 07:00:00,April,14,1899-12-30 08:20:00,0
19446,Vietravel Airlines,Promo1 (P) - Vé không hoàn,TP HCM,Đà Nẵng,April,14,1899-12-30 07:35:00,April,14,1899-12-30 08:55:00,0
19447,Vietravel Airlines,Promo1 (P) - Vé không hoàn,Đà Nẵng,TP HCM,April,14,1899-12-30 10:35:00,April,14,1899-12-30 12:05:00,0
19448,Vietravel Airlines,Promo1 (P) - Vé không hoàn,Hà Nội,Đà Nẵng,April,14,1899-12-30 12:10:00,April,14,1899-12-30 01:30:00,0

In [9]:
# Processing datetime
X['Month_from'] = pd.to_datetime(X['Month_from'], format='%B').dt.month
X['Month_to'] = pd.to_datetime(X['Month_to'], format='%B').dt.month

X['hour_from'] = pd.to_datetime(X['time_from']).dt.hour
X['minute_from'] = pd.to_datetime(X['time_from']).dt.minute


X['hour_to'] = pd.to_datetime(X['time_to']).dt.hour
X['minute_to'] = pd.to_datetime(X['time_to']).dt.minute

X = X.drop(columns=['time_from', 'time_to'])
X, y

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_10628\2704928731.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Month_from'] = pd.to_datetime(X['Month_from'], format='%B').dt.month
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_10628\2704928731.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Month_to'] = pd.to_datetime(X['Month_to'], format='%B').dt.month
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_10628\2704928731.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['hour_from'] = pd.to_datetime(X['time_from']).dt.hour

(                code_name                        type      from        to  \
 0        Vietnam Airlines              Economy (EG)-M    Hà Nội    TP HCM
 1        Vietnam Airlines              Economy (EG)-M    TP HCM    Hà Nội
 2        Vietnam Airlines             Business (BF)-J  Phú Quốc    Hà Nội
 3        Vietnam Airlines             Business (BF)-J  Phú Quốc    Hà Nội
 4        Vietnam Airlines             Business (BF)-J    Hà Nội  Phú Quốc
 ...                   ...                         ...       ...       ...
 19444  Vietravel Airlines  Promo1 (P) - Vé không hoàn    TP HCM   Đà Nẵng
 19445  Vietravel Airlines  Promo1 (P) - Vé không hoàn   Đà Nẵng    Hà Nội
 19446  Vietravel Airlines  Promo1 (P) - Vé không hoàn    TP HCM   Đà Nẵng
 19447  Vietravel Airlines  Promo1 (P) - Vé không hoàn   Đà Nẵng    TP HCM
 19448  Vietravel Airlines  Promo1 (P) - Vé không hoàn    Hà Nội   Đà Nẵng

        Month_from  Day_from  Month_to  Day_to  is_holiday  hour_from  \
 0               4         6         4       6           0          7
 1               5         3         5       3           1          9
 2               4         4         4       4           0          3
 3               4        25         4      25           0          7
 4               4        30         4      30           1          3
 ...           ...       ...       ...     ...         ...        ...
 19444           4        14         4      14           0          4
 19445           4        14         4      14           0          7
 19446           4        14         4      14           0          7
 19447           4        14         4      14           0         10
 19448           4        14         4      14           0         12

        minute_from  hour_to  minute_to
 0                0        9         15
 1                0       11         10
 2               45        6          0
 3                0        9         15
 4               20        5         35
 ...            ...      ...        ...
 19444            0        5         20
 19445            0        8         20
 19446           35        8         55
 19447           35       12          5
 19448           10        1         30

 [19449 rows x 13 columns],
        Sum of Sum of total_price
 0                        7464000
 1                        7464000
 2                        6460000
 3                        6460000
 4                        6460000
 ...                          ...
 19444                     680600
 19445                     680600
 19446                     680600
 19447                     680600
 19448                     680600

 [19449 rows x 1 columns])

In [10]:
X['hour_sin_from'] = np.sin(2 * np.pi * X['hour_from'] / 24)
X['hour_cos_from'] = np.cos(2 * np.pi * X['hour_from'] / 24)
X['minute_sin_from'] = np.sin(2 * np.pi * X['minute_from'] / 60)
X['minute_cos_from'] = np.cos(2 * np.pi * X['minute_from'] / 60)

X['hour_sin_to'] = np.sin(2 * np.pi * X['hour_to'] / 24)
X['hour_cos_to'] = np.cos(2 * np.pi * X['hour_to'] / 24)
X['minute_sin_to'] = np.sin(2 * np.pi * X['minute_to'] / 60)
X['minute_cos_to'] = np.cos(2 * np.pi * X['minute_to'] / 60)

X = X.drop(columns=['hour_from', 'minute_from', 'hour_to', 'minute_to','Month_from','Day_from',	'Month_to',	'Day_to'])
X

,code_name,type,from,to,is_holiday,hour_sin_from,hour_cos_from,minute_sin_from,minute_cos_from,hour_sin_to,hour_cos_to,minute_sin_to,minute_cos_to
0,Vietnam Airlines,Economy (EG)-M,Hà Nội,TP HCM,0,9.659258e-01,-0.258819,0.000000,1.000000e+00,7.071068e-01,-7.071068e-01,1.000000e+00,2.832769e-16
1,Vietnam Airlines,Economy (EG)-M,TP HCM,Hà Nội,1,7.071068e-01,-0.707107,0.000000,1.000000e+00,2.588190e-01,-9.659258e-01,8.660254e-01,5.000000e-01
2,Vietnam Airlines,Business (BF)-J,Phú Quốc,Hà Nội,0,7.071068e-01,0.707107,-1.000000,-1.836970e-16,1.000000e+00,6.123234e-17,0.000000e+00,1.000000e+00
3,Vietnam Airlines,Business (BF)-J,Phú Quốc,Hà Nội,0,9.659258e-01,-0.258819,0.000000,1.000000e+00,7.071068e-01,-7.071068e-01,1.000000e+00,2.832769e-16
4,Vietnam Airlines,Business (BF)-J,Hà Nội,Phú Quốc,1,7.071068e-01,0.707107,0.866025,-5.000000e-01,9.659258e-01,2.588190e-01,-5.000000e-01,-8.660254e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19444,Vietravel Airlines,Promo1 (P) - Vé không hoàn,TP HCM,Đà Nẵng,0,8.660254e-01,0.500000,0.000000,1.000000e+00,9.659258e-01,2.588190e-01,8.660254e-01,-5.000000e-01
19445,Vietravel Airlines,Promo1 (P) - Vé không hoàn,Đà Nẵng,Hà Nội,0,9.659258e-01,-0.258819,0.000000,1.000000e+00,8.660254e-01,-5.000000e-01,8.660254e-01,-5.000000e-01
19446,Vietravel Airlines,Promo1 (P) - Vé không hoàn,TP HCM,Đà Nẵng,0,9.659258e-01,-0.258819,-0.500000,-8.660254e-01,8.660254e-01,-5.000000e-01,-5.000000e-01,8.660254e-01
19447,Vietravel Airlines,Promo1 (P) - Vé không hoàn,Đà Nẵng,TP HCM,0,5.000000e-01,-0.866025,-0.500000,-8.660254e-01,1.224647e-16,-1.000000e+00,5.000000e-01,8.660254e-01
19448,Vietravel Airlines,Promo1 (P) - Vé không hoàn,Hà Nội,Đà Nẵng,0,1.224647e-16,-1.000000,0.866025,5.000000e-01,2.588190e-01,9.659258e-01,5.665539e-16,-1.000000e+00

In [11]:
# Chia tập train và test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42 # Khong dùng stratify=y trong  thuật toán linear
)
X_train

,code_name,type,from,to,is_holiday,hour_sin_from,hour_cos_from,minute_sin_from,minute_cos_from,hour_sin_to,hour_cos_to,minute_sin_to,minute_cos_to
11709,Bamboo Airways,Eco Saver,Đà Nẵng,TP HCM,0,0.500000,-8.660254e-01,8.660254e-01,0.500000,0.258819,-9.659258e-01,-8.660254e-01,-0.500000
14034,Vietjet,Eco,TP HCM,Đà Lạt,0,0.965926,-2.588190e-01,-8.660254e-01,-0.500000,0.866025,-5.000000e-01,-5.000000e-01,-0.866025
8086,Vietjet,Eco,Quy Nhơn,Hà Nội,0,0.866025,-5.000000e-01,8.660254e-01,-0.500000,0.707107,-7.071068e-01,-5.000000e-01,0.866025
11800,Bamboo Airways,Eco Saver,Hà Nội,Đà Lạt,1,0.965926,2.588190e-01,5.665539e-16,-1.000000,0.965926,-2.588190e-01,8.660254e-01,-0.500000
15460,Pacific Airlines,Economy (EL)-A,TP HCM,Vinh,0,0.965926,2.588190e-01,8.660254e-01,0.500000,0.965926,-2.588190e-01,0.000000e+00,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,Vietjet,Eco,TP HCM,Hà Nội,0,0.866025,-5.000000e-01,-8.660254e-01,-0.500000,0.258819,-9.659258e-01,0.000000e+00,1.000000
11964,Vietnam Airlines,Economy (EL)-A,TP HCM,Hải Phòng,0,0.866025,5.000000e-01,-5.000000e-01,0.866025,0.965926,-2.588190e-01,0.000000e+00,1.000000
5390,Pacific Airlines,Economy (EC)-E,TP HCM,Hà Nội,1,0.866025,-5.000000e-01,5.665539e-16,-1.000000,0.500000,-8.660254e-01,-5.000000e-01,0.866025
860,Vietnam Airlines,Economy (EC)-Q,Hà Nội,Phú Quốc,0,1.000000,6.123234e-17,5.000000e-01,-0.866025,0.866025,-5.000000e-01,5.665539e-16,-1.000000
15795,Vietnam Airlines,Economy (EL)-A,TP HCM,Đà Lạt,0,0.965926,2.588190e-01,-8.660254e-01,0.500000,1.000000,6.123234e-17,-5.000000e-01,0.866025

In [12]:
Transformers = [
    ('code_name', OneHotEncoder(handle_unknown='ignore', sparse_output=True), ['code_name']),
    ('from', OneHotEncoder(handle_unknown='ignore', sparse_output=True), ['from']),
    ('to', OneHotEncoder(handle_unknown='ignore', sparse_output=True), ['to']),
    ('type', OneHotEncoder(handle_unknown='ignore', sparse_output=True), ['type'])    
]

In [13]:
col_tf = ColumnTransformer(transformers=Transformers, remainder='passthrough') # remainder='passthrough': giữ nguyên các cột khong đc transform khác

X_train = col_tf.fit_transform(X_train) # fit là quá trình đo đạc, còn transform là quá trình biến đổi theo sự đo đạc đó
X_test = col_tf.transform(X_test)
X_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 46748 stored elements and shape (3890, 80)>

In [14]:
# Training model bằng sklearn
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [15]:
# Tính toán các chỉ số
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"--- Kết quả đánh giá ---")
print(f"R-squared (R2): {r2:.4f}")# Càng gần 1 càng tốt (độ khớp của mô hình)
print(f"Mean Absolute Error (MAE): {mae:.4f}") # Sai số trung bình (đơn vị giống y)
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}") # Sai số căn lề (phạt nặng sai số lớn)

--- Kết quả đánh giá ---
R-squared (R2): 0.7214
Mean Absolute Error (MAE): 215205.4740
Root Mean Squared Error (RMSE): 345339.9131

In [16]:
y_pred

array([[ 867296.8015101 ],
       [1123706.81014917],
       [ 938677.94922691],
       ...,
       [1156324.42704463],
       [ 592228.89394891],
       [1014284.68580084]], shape=(3890, 1))

- Đánh giá việc MAE và RMAE có khoảng cách càng lớn thì outlier càng nhiều