In [213]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [214]:
df = pd.read_excel("D:/AI_VIETNAM/file/study_score.xlsx")
df

  Sinh viên  Giờ học (X1)  Giờ ngủ (X2) Kết quả (ycls)  Điểm thi (yreg)
0        P1             2             8          Trượt              4.5
1        P2             3             7          Trượt              5.5
2        P3             5             6            Đậu              7.5
3        P4             6             5            Đậu              8.5
4        P5             4             6            Đậu              7.0

In [215]:
df = df.rename(columns={"Sinh viên":"Id","Giờ học (X1)":"time_study", "Giờ ngủ (X2)":"time_sleep", "Kết quả (ycls)":"predict", "Điểm thi (yreg)":"score"})
df

   Id  time_study  time_sleep predict  score
0  P1           2           8   Trượt    4.5
1  P2           3           7   Trượt    5.5
2  P3           5           6     Đậu    7.5
3  P4           6           5     Đậu    8.5
4  P5           4           6     Đậu    7.0

In [216]:
# Bước 1: Chọn số điểm gần nhất K
k = 3
# Bước 2: Chuẩn hóa data và gán label
df['time_sleep'] = [(x-5)/3 for x in df.time_sleep]
df['time_study'] = [(x-2)/4 for x in df.time_study]
df['predict']=[0 if x=="Trượt" else 1 for x in df.predict]
df

   Id  time_study  time_sleep  predict  score
0  P1        0.00    1.000000        0    4.5
1  P2        0.25    0.666667        0    5.5
2  P3        0.75    0.333333        1    7.5
3  P4        1.00    0.000000        1    8.5
4  P5        0.50    0.333333        1    7.0

In [ ]:
# Bước 3: Tính d(p_new, p_old)
# x_test = [7,4]
new_time_study = (4-2)/4
new_time_sleep = (7-5)/3
p_new = [np.sqrt((new_time_study-df.time_study)**2 + (new_time_sleep-df.time_sleep)**2)]
# Bước 4: sort and select
index = np.argsort(p_new)
for i in index:
    index = np.array(i)
index

array([1, 4, 2, 0, 3])

In [218]:
# Dự đoán điểm thi của p_new
#Cach 1
sort = np.sort(p_new)
mean=0
for i in range(0,3):
    mean += p_new[0][i]
mean /= 3
print(mean)
#Cach 2
w = 1 / sort
y=0
x=0
for i in range(0,3):
    y += w[0][i] * df['predict'][index[i]]
    x += w[0][i]
y/x

0.42253062641466604

np.float64(0.574468085106383)